# ================== 开发环境配置 ==================
server:
  port: 8080  # 开发环境端口

# ================== Spring 相关配置 ==================
spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${sky.datasource.username}
    password: ${sky.datasource.password}

  # Redis 配置
  data:
    redis:
      host: ${sky.redis.host}
      port: ${sky.redis.port}
      database: ${sky.redis.database}
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0

# ================== 自定义配置的具体值 ==================
sky:
#  # JWT配置（已有但不完善，在SystemConstant里）
#  jwt:
#    admin-secret-key: itcast
#    admin-ttl: 72000000
#    admin-token-name: token
#    user-secret-key: itheima
#    user-ttl: 72000000
#    user-token-name: authentication

  # 数据源具体值
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost    #101.132.149.165   # 如果是远程开发就用IP，本地开发就用localhost
    port: 3306
    database: nursing_system
    username: root
    password: root

  # Redis具体值
  redis:
    host: localhost
    port: 6379
    database: 0

  # 阿里云OSS配置
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: 
    access-key-secret: 
    bucket-name: java-sky-z


# ================== 开发环境专用日志 ==================
logging:
  level:
    com.example.nursingsystem.mapper: INFO  # SQL日志
    com.example.nursingsystem.service: INFO
    com.example.nursingsystem.controller: INFO
